# Generated by Django 5.2.7 on 2026-07-02 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todo.project'),
        ),
    ]
